name: PlatformIO Library Release

on:
    release:
        types: [published]
    workflow_dispatch:
        inputs:
            version:
                description: 'Version to release'
                required: true
                default: '1.6.0'

jobs:
    validate:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform: [uno, megaatmega2560]
                example:
                    [
                        WebClient,
                        DhcpChatServer,
                        WebServer,
                        MulticastReceiver,
                        UDPSendReceiveString,
                        HTTPServer
                    ]
                exclude:
                    # Exclude resource-intensive examples on smaller platforms
                    - platform: uno
                      example: HTTPServer

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install PlatformIO
              run: |
                  pip install platformio
                  pio update
                  pio upgrade --dev

            - name: Build Example
              run: |
                  pio ci examples/${{ matrix.example }} --board=${{ matrix.platform }} --lib=./

    release:
        needs: validate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: '3.x'

            - name: Install PlatformIO
              run: |
                  pip install platformio
                  pio upgrade --dev

            - name: Update Version
              run: |
                  if [ "${{ github.event_name }}" == "release" ]; then
                    VERSION=${GITHUB_REF#refs/tags/v}
                  else
                    VERSION=${{ github.event.inputs.version }}
                  fi
                  sed -i "s/\"version\": \".*\"/\"version\": \"$VERSION\"/" library.json
                  sed -i "s/version=.*/version=$VERSION/" library.properties

            - name: Login to PlatformIO
              run: |
                  pio account login --username "${{ secrets.PLATFORMIO_USERNAME }}" --password "${{ secrets.PLATFORMIO_PASSWORD }}"

            - name: Package Library
              run: |
                  mkdir -p dist
                  pio package pack --output ./dist/

            - name: Publish to Registry
              run: |
                  pio package publish ./dist/*.tar.gz --no-interactive

            - name: Upload Release Assets
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./dist/Ethernet3-${{ github.event.release.tag_name }}.tar.gz
                  asset_name: Ethernet3-${{ github.event.release.tag_name }}.tar.gz
                  asset_content_type: application/gzip
